---
- name: Configuracao base o ambiente de Test Drive
  hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: False
  tasks:

#####################
#### Base do AAP ####
#####################
  - name: Criar inventory INV-ALL-HOSTS
    ansible.controller.inventory:
      name: INV-ALL-HOSTS
      description: "Inventario com hosts dos student"
      organization: Default
      state: present

#  - name: Adicionar hosts coletados
#    ansible.controller.host:
#      name: "{{ item.1.name }}"
#      inventory: INV-ALL-HOSTS
#      enabled: True
#      variables:
#        ansible_host: "{{ item.1.ip }}"
#    loop: "{{ student_hosts | subelements('hosts') }}"
#    loop_control:
#      label: "{{ item.1.name }}"


  - name: Adicionar hosts coletados
    ansible.controller.host:
      name: "{{ item.0.student }}-{{ item.1.name }}"
      inventory: INV-ALL-HOSTS
      enabled: True
      variables:
        ansible_host: "{{ item.1.ip }}"
    loop: "{{ student_hosts | subelements('hosts') }}"

  - name: Criar grupos de estudantes e adicionar hosts
    ansible.controller.group:
      name: "{{ item.student }}"
      inventory: INV-ALL-HOSTS
      preserve_existing_hosts: True
    loop: "{{ student_hosts }}"
    register: group_creation

  - name: Adicionar hosts aos grupos de estudantes
    ansible.controller.group:
      name: "{{ item.0.student }}"
      inventory: INV-ALL-HOSTS
      hosts: "{{ item.0.student }}-{{ item.1.name }}"
    loop: "{{ student_hosts | subelements('hosts') }}"